language: ruby
rvm:
  - 1.8.7
  - ree
  - 1.9.3
  - 2.0.0
  - rbx-19mode
  - jruby
script: bundle exec rake test
env:
  - DEVISE_ORM=active_record
  - DEVISE_ORM=mongoid
gemfile:
  - gemfiles/Gemfile.rails-3.2.x
  - Gemfile
services:
  - mongodb
matrix:
  exclude:
    - rvm: 1.8.7 
      gemfile: Gemfile
    - rvm: ree
      gemfile: Gemfile
